const { generateImage } = require('../lib/ai');
const { channelInfo } = require('../lib/messageConfig');

async function imagineCommand(sock, chatId, message) {
    try {
        const text = message.message?.conversation?.trim() ||
                     message.message?.extendedTextMessage?.text?.trim() || '';

        // Remove command prefix (.imagine)
        const prompt = text.replace(/^\.\w+\s*/, '').trim();

        if (!prompt) {
            return await sock.sendMessage(chatId, {
                text: '🎨 Please provide a prompt for image generation.\nExample: .imagine a beautiful sunset over mountains',
                ...channelInfo
            }, { quoted: message });
        }

        await sock.sendMessage(chatId, {
            react: { text: '🎨', key: message.key }
        });

        await sock.sendMessage(chatId, {
            text: '🎨 Generating your image... Please wait.',
            ...channelInfo
        }, { quoted: message });

        const imageBuffer = await generateImage(prompt);

        if (!imageBuffer) {
            return await sock.sendMessage(chatId, {
                text: '❌ Failed to generate image. Gemini may be temporarily unavailable — please try again later.',
                ...channelInfo
            }, { quoted: message });
        }

        await sock.sendMessage(chatId, {
            image: imageBuffer,
            caption: `🎨 *${prompt}*\n\n> Generated by Optimus Bot`,
            ...channelInfo
        }, { quoted: message });

    } catch (error) {
        console.error('Error in imagine command:', error.message);
        await sock.sendMessage(chatId, {
            text: '❌ Failed to generate image. Please try again later.',
            ...channelInfo
        }, { quoted: message });
    }
}

module.exports = imagineCommand;
