#!/usr/bin/env node
/**
 * pair.js — link WhatsApp on YOUR machine and write ./session/creds.json.
 *
 * Why this exists: linking normally happens inside the bot's own console, which
 * on a panel you may not be able to see or interact with. This script does ONLY
 * the linking step, wherever you can watch the output, and writes the same
 * ./session/ directory the bot reads at startup. Copy that folder to the host
 * and the bot connects with no phone number configured anywhere.
 *
 * Usage
 *   node scripts/pair.js 923701609799        pairing code (recommended)
 *   node scripts/pair.js 923701609799 --qr   QR in the terminal
 *   node scripts/pair.js                     falls back to settings.ownerNumber
 *
 * It mirrors index.js's auth state and socket options, so the session it writes
 * is exactly what the bot expects.
 *
 * ⚠️  SECURITY — read this before using a third-party "pair code" website.
 * session/creds.json IS the account login: the Noise key pair, identity keys and
 * the linked JID. Whoever's instance called requestPairingCode holds those
 * private keys, so a creds.json generated by someone else's service is not
 * "your" session — it is a copy of theirs, and they keep working access to the
 * account. Generate it HERE, on your own machine. Pairing is cryptographically
 * bound to the requester; there is no way to have a third party mint one for you
 * safely.
 */
const fs = require('fs');
const path = require('path');
const pino = require('pino');
const NodeCache = require('node-cache');
const {
    default: makeWASocket,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
    DisconnectReason,
    makeCacheableSignalKeyStore,
} = require('@whiskeysockets/baileys');

const SESSION_DIR = path.join(__dirname, '..', 'session');
const CREDS_FILE = path.join(SESSION_DIR, 'creds.json');

function fail(message) {
    console.error(`\n✖ ${message}\n`);
    process.exit(1);
}

function digitsOnly(value) {
    return String(value || '').replace(/[^0-9]/g, '');
}

/** The number to link: first bare argument, else settings.ownerNumber. */
function resolvePhoneNumber(args) {
    const fromArgs = args.find((a) => /^\+?[0-9][0-9\s-]*$/.test(a));
    if (fromArgs) return digitsOnly(fromArgs);
    try {
        return digitsOnly(require('../settings').ownerNumber);
    } catch {
        return '';
    }
}

async function main() {
    const args = process.argv.slice(2);
    const useQr = args.includes('--qr');
    const phoneNumber = resolvePhoneNumber(args);

    fs.mkdirSync(SESSION_DIR, { recursive: true });
    const { state, saveCreds } = await useMultiFileAuthState(SESSION_DIR);

    // Check this BEFORE anything about phone numbers: an already-linked session
    // needs no number at all, and warning about one would be noise.
    if (state.creds?.registered) {
        console.log('\n✅ This session is already linked — nothing to do.');
        console.log(`   Session folder: ${SESSION_DIR}`);
        console.log('\n   Copy the WHOLE folder to your host and the bot will connect on startup.');
        console.log('   To link a different account, delete the session folder and run this again.\n');
        process.exit(0);
    }

    if (!useQr && !phoneNumber) {
        fail(
            'No phone number given.\n' +
                '  node scripts/pair.js 923701609799\n' +
                '  node scripts/pair.js 923701609799 --qr\n' +
                '  (or set ownerNumber in settings.js)'
        );
    }

    if (!useQr) {
        // Warn only. The library's metadata lags reality — +923701609799 is a
        // working Pakistani number whose 370 prefix it does not recognise, so a
        // hard failure here would block linking outright. WhatsApp decides.
        const parsed = require('awesome-phonenumber')('+' + phoneNumber);
        if (!parsed.isValid()) {
            console.log(
                `⚠️  ${phoneNumber} is not recognised as a valid number (region: ${parsed.getRegionCode() || 'unknown'}).`
            );
            console.log('   Continuing — WhatsApp will reject it if it is wrong.\n');
        }
    }

    const { version } = await fetchLatestBaileysVersion();
    const sock = makeWASocket({
        version,
        logger: pino({ level: 'silent' }),
        // v7 ignores this, but keep it false in QR mode so nothing misleading is logged.
        printQRInTerminal: false,
        browser: ['Ubuntu', 'Chrome', '20.0.04'],
        auth: {
            creds: state.creds,
            keys: makeCacheableSignalKeyStore(state.keys, pino({ level: 'fatal' }).child({ level: 'fatal' })),
        },
        markOnlineOnConnect: true,
        syncFullHistory: false,
        msgRetryCounterCache: new NodeCache(),
        defaultQueryTimeoutMs: 60000,
        connectTimeoutMs: 60000,
        keepAliveIntervalMs: 10000,
    });

    sock.ev.on('creds.update', saveCreds);

    if (!useQr) {
        // Give the socket a moment to reach the server before asking, as the bot does.
        setTimeout(async () => {
            try {
                let code = await sock.requestPairingCode(phoneNumber);
                code = code?.match(/.{1,4}/g)?.join('-') || code;
                console.log('\n  ┌────────────────────────────────┐');
                console.log(`  │   Pairing code:  ${code}`);
                console.log('  └────────────────────────────────┘');
                console.log('\n  1. Open WhatsApp on that phone');
                console.log('  2. Settings → Linked Devices → Link a Device');
                console.log('  3. Tap "Link with phone number instead"');
                console.log(`  4. Enter: ${code}\n`);
            } catch (err) {
                fail(`Could not request a pairing code: ${err.message}`);
            }
        }, 3000);
    }

    sock.ev.on('connection.update', (update) => {
        const { connection, lastDisconnect, qr } = update;

        if (qr && useQr) {
            console.log('\n  Scan this with WhatsApp → Settings → Linked Devices:\n');
            try {
                require('qrcode-terminal').generate(qr, { small: true });
            } catch (err) {
                fail(`Could not render the QR code: ${err.message}\nUse a pairing code instead.`);
            }
        }

        if (connection === 'open') {
            console.log('\n✅ Linked successfully.');
            console.log(`   Credentials: ${CREDS_FILE}`);
            console.log('\n   Next: copy the WHOLE session folder to your host:');
            console.log(`         ${SESSION_DIR}  →  <host>/session/`);
            console.log('   Then restart the bot — it connects on startup with no phone number needed.\n');
            setTimeout(() => process.exit(0), 1500);
        }

        if (connection === 'close') {
            const statusCode = lastDisconnect?.error?.output?.statusCode;
            if (statusCode === DisconnectReason.loggedOut) {
                fail('WhatsApp rejected the link (logged out). Delete session/ and run this again.');
            }
            console.error(`   Connection closed (code ${statusCode ?? 'unknown'}) — retrying…`);
        }
    });
}

main().catch((err) => fail(err?.stack || err?.message || String(err)));
